---
- name: Test actions locales
  # Playbook complet en local, alternative à delegate_to & local_action
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    MA_VARIABLE_DANS_LE_FICHIER: Gwen

  tasks:
    - name: Utiliser hello.txt comme modèle pour générer hello_copy.txt
      ansible.builtin.template:
        src: ./templates/hello.txt
        dest: ./templates/jecopiehello.md
        owner: Gwen
        group: staff
        mode: '0644'

